package com.aiep.sesamet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DoctorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorAllPropertiesEquals(Doctor expected, Doctor actual) {
        assertDoctorAutoGeneratedPropertiesEquals(expected, actual);
        assertDoctorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorAllUpdatablePropertiesEquals(Doctor expected, Doctor actual) {
        assertDoctorUpdatableFieldsEquals(expected, actual);
        assertDoctorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorAutoGeneratedPropertiesEquals(Doctor expected, Doctor actual) {
        assertThat(expected)
            .as("Verify Doctor auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorUpdatableFieldsEquals(Doctor expected, Doctor actual) {
        assertThat(expected)
            .as("Verify Doctor relevant properties")
            .satisfies(e -> assertThat(e.getRut_doctor()).as("check rut_doctor").isEqualTo(actual.getRut_doctor()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getApellido_paterno()).as("check apellido_paterno").isEqualTo(actual.getApellido_paterno()))
            .satisfies(e -> assertThat(e.getApellido_materno()).as("check apellido_materno").isEqualTo(actual.getApellido_materno()))
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()))
            .satisfies(e -> assertThat(e.getCorreo()).as("check correo").isEqualTo(actual.getCorreo()))
            .satisfies(e -> assertThat(e.getEspecialidad()).as("check especialidad").isEqualTo(actual.getEspecialidad()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorUpdatableRelationshipsEquals(Doctor expected, Doctor actual) {
        // empty method
    }
}
